---

# TODO: Argument validation.
#
# TODO: Set defaults as needed: lvm_vg, device_name, disks

#
# Resolve specified disks to device node paths.
#
- name: Resolve disks
  resolve_blockdev:
    spec: "{{ item }}"
  with_items: "{{ disks }}"
  register: resolved_disks

- debug:
    var: resolved_disks

- name: set list of resolved disk paths
  set_fact:
    disk_paths: "{{ resolved_disks.results|map(attribute='device')|list }}"

- name: Show disks
  debug:
    var: disk_paths

#
# Set the path for the final device based on device type.
#
- name: set final device path for whole disk
  set_fact:
    device_path: "{{ disk_paths[0] }}"
  when: device_type == "disk"

- name: set final device path for lv
  set_fact:
    device_path: "/dev/mapper/{{ lvm_vg }}-{{ device_name }}"
  when: device_type == "lvm"

- debug:
    var: device_path

- name: Remove the Specified Storage Volume
  include_tasks: "{{ layer }}-{{ storage_backend }}.yml"
  with_items: "{{ storage_layers[::-1] }}"
  loop_control:
    loop_var: layer
  when: state == "absent"


- name: Configure the Specified Storage Volume
  include_tasks: "{{ layer }}-{{ storage_backend }}.yml"
  with_items: "{{ storage_layers }}"
  loop_control:
    loop_var: layer
  when: state == "present"

#
# Update facts since we may have changed system state.
#
# Should this be in a handler instead?
#
- name: Update facts
  setup:
