---
- name: Install parted for partition management
  package:
    name: parted
    state: present
  register: parted_installed
  # update this condition when current use_partitions issue (#5) is fixed.
  when: "use_partitions and ['parted'] is not subset(ansible_facts.packages.keys()) \
         and parted_installed is undefined and not ansible_check_mode"

- block:
  - name: set up partition parameters
    set_fact:
      part_info: "{{ part_defaults|combine({'disk': disk,
                                            'size': '100%',
                                            'name': pool.name + ' ' + disk_idx|string,
                                            'state': pool.state}) }}" # FIXME: state should support switching member types between disk and partition
  - name: manage partition
    include_tasks: partition-{{ storage_backend }}.yml
  when: use_partitions
